// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcTest.proto

package com.github.chenmingq.rpc.common.transport.protocol;

public final class RpcTestProto {
  private RpcTestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqConnectServerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqConnectServerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 本机暴露的端口
     * </pre>
     *
     * <code>int32 port = 1;</code>
     */
    int getPort();

    /**
     * <pre>
     * 本机暴露的节点id
     * </pre>
     *
     * <code>int32 node = 2;</code>
     */
    int getNode();
  }
  /**
   * <pre>
   * 连接服务
   * </pre>
   *
   * Protobuf type {@code ReqConnectServerMessage}
   */
  public  static final class ReqConnectServerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReqConnectServerMessage)
      ReqConnectServerMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqConnectServerMessage.newBuilder() to construct.
    private ReqConnectServerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqConnectServerMessage() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReqConnectServerMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqConnectServerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              port_ = input.readInt32();
              break;
            }
            case 16: {

              node_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcTestProto.internal_static_ReqConnectServerMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcTestProto.internal_static_ReqConnectServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReqConnectServerMessage.class, Builder.class);
    }

    public static final int PORT_FIELD_NUMBER = 1;
    private int port_;
    /**
     * <pre>
     * 本机暴露的端口
     * </pre>
     *
     * <code>int32 port = 1;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int NODE_FIELD_NUMBER = 2;
    private int node_;
    /**
     * <pre>
     * 本机暴露的节点id
     * </pre>
     *
     * <code>int32 node = 2;</code>
     */
    public int getNode() {
      return node_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (port_ != 0) {
        output.writeInt32(1, port_);
      }
      if (node_ != 0) {
        output.writeInt32(2, node_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, port_);
      }
      if (node_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, node_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReqConnectServerMessage)) {
        return super.equals(obj);
      }
      ReqConnectServerMessage other = (ReqConnectServerMessage) obj;

      if (getPort()
          != other.getPort()) return false;
      if (getNode()
          != other.getNode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + NODE_FIELD_NUMBER;
      hash = (53 * hash) + getNode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReqConnectServerMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReqConnectServerMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReqConnectServerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReqConnectServerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReqConnectServerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReqConnectServerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReqConnectServerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReqConnectServerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReqConnectServerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReqConnectServerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReqConnectServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReqConnectServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReqConnectServerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 连接服务
     * </pre>
     *
     * Protobuf type {@code ReqConnectServerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqConnectServerMessage)
        ReqConnectServerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcTestProto.internal_static_ReqConnectServerMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcTestProto.internal_static_ReqConnectServerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReqConnectServerMessage.class, Builder.class);
      }

      // Construct using com.github.chenmingq.rpc.common.transport.protocol.RpcTestProto.ReqConnectServerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        port_ = 0;

        node_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcTestProto.internal_static_ReqConnectServerMessage_descriptor;
      }

      @Override
      public ReqConnectServerMessage getDefaultInstanceForType() {
        return ReqConnectServerMessage.getDefaultInstance();
      }

      @Override
      public ReqConnectServerMessage build() {
        ReqConnectServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ReqConnectServerMessage buildPartial() {
        ReqConnectServerMessage result = new ReqConnectServerMessage(this);
        result.port_ = port_;
        result.node_ = node_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReqConnectServerMessage) {
          return mergeFrom((ReqConnectServerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReqConnectServerMessage other) {
        if (other == ReqConnectServerMessage.getDefaultInstance()) return this;
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getNode() != 0) {
          setNode(other.getNode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReqConnectServerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReqConnectServerMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int port_ ;
      /**
       * <pre>
       * 本机暴露的端口
       * </pre>
       *
       * <code>int32 port = 1;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <pre>
       * 本机暴露的端口
       * </pre>
       *
       * <code>int32 port = 1;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 本机暴露的端口
       * </pre>
       *
       * <code>int32 port = 1;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int node_ ;
      /**
       * <pre>
       * 本机暴露的节点id
       * </pre>
       *
       * <code>int32 node = 2;</code>
       */
      public int getNode() {
        return node_;
      }
      /**
       * <pre>
       * 本机暴露的节点id
       * </pre>
       *
       * <code>int32 node = 2;</code>
       */
      public Builder setNode(int value) {
        
        node_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 本机暴露的节点id
       * </pre>
       *
       * <code>int32 node = 2;</code>
       */
      public Builder clearNode() {
        
        node_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReqConnectServerMessage)
    }

    // @@protoc_insertion_point(class_scope:ReqConnectServerMessage)
    private static final ReqConnectServerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReqConnectServerMessage();
    }

    public static ReqConnectServerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqConnectServerMessage>
        PARSER = new com.google.protobuf.AbstractParser<ReqConnectServerMessage>() {
      @Override
      public ReqConnectServerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqConnectServerMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqConnectServerMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReqConnectServerMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public ReqConnectServerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResProviderAddressMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResProviderAddressMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 地址列表
     * </pre>
     *
     * <code>repeated .AddressBean addrList = 1;</code>
     */
    java.util.List<AddressBean>
        getAddrListList();
    /**
     * <pre>
     * 地址列表
     * </pre>
     *
     * <code>repeated .AddressBean addrList = 1;</code>
     */
    AddressBean getAddrList(int index);
    /**
     * <pre>
     * 地址列表
     * </pre>
     *
     * <code>repeated .AddressBean addrList = 1;</code>
     */
    int getAddrListCount();
    /**
     * <pre>
     * 地址列表
     * </pre>
     *
     * <code>repeated .AddressBean addrList = 1;</code>
     */
    java.util.List<? extends AddressBeanOrBuilder>
        getAddrListOrBuilderList();
    /**
     * <pre>
     * 地址列表
     * </pre>
     *
     * <code>repeated .AddressBean addrList = 1;</code>
     */
    AddressBeanOrBuilder getAddrListOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 返回注册中心的提供者地址列表
   * </pre>
   *
   * Protobuf type {@code ResProviderAddressMessage}
   */
  public  static final class ResProviderAddressMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResProviderAddressMessage)
      ResProviderAddressMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResProviderAddressMessage.newBuilder() to construct.
    private ResProviderAddressMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResProviderAddressMessage() {
      addrList_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResProviderAddressMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResProviderAddressMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                addrList_ = new java.util.ArrayList<AddressBean>();
                mutable_bitField0_ |= 0x00000001;
              }
              addrList_.add(
                  input.readMessage(AddressBean.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          addrList_ = java.util.Collections.unmodifiableList(addrList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcTestProto.internal_static_ResProviderAddressMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcTestProto.internal_static_ResProviderAddressMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResProviderAddressMessage.class, Builder.class);
    }

    public static final int ADDRLIST_FIELD_NUMBER = 1;
    private java.util.List<AddressBean> addrList_;
    /**
     * <pre>
     * 地址列表
     * </pre>
     *
     * <code>repeated .AddressBean addrList = 1;</code>
     */
    public java.util.List<AddressBean> getAddrListList() {
      return addrList_;
    }
    /**
     * <pre>
     * 地址列表
     * </pre>
     *
     * <code>repeated .AddressBean addrList = 1;</code>
     */
    public java.util.List<? extends AddressBeanOrBuilder>
        getAddrListOrBuilderList() {
      return addrList_;
    }
    /**
     * <pre>
     * 地址列表
     * </pre>
     *
     * <code>repeated .AddressBean addrList = 1;</code>
     */
    public int getAddrListCount() {
      return addrList_.size();
    }
    /**
     * <pre>
     * 地址列表
     * </pre>
     *
     * <code>repeated .AddressBean addrList = 1;</code>
     */
    public AddressBean getAddrList(int index) {
      return addrList_.get(index);
    }
    /**
     * <pre>
     * 地址列表
     * </pre>
     *
     * <code>repeated .AddressBean addrList = 1;</code>
     */
    public AddressBeanOrBuilder getAddrListOrBuilder(
        int index) {
      return addrList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < addrList_.size(); i++) {
        output.writeMessage(1, addrList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < addrList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, addrList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ResProviderAddressMessage)) {
        return super.equals(obj);
      }
      ResProviderAddressMessage other = (ResProviderAddressMessage) obj;

      if (!getAddrListList()
          .equals(other.getAddrListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAddrListCount() > 0) {
        hash = (37 * hash) + ADDRLIST_FIELD_NUMBER;
        hash = (53 * hash) + getAddrListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ResProviderAddressMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResProviderAddressMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResProviderAddressMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResProviderAddressMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResProviderAddressMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResProviderAddressMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResProviderAddressMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResProviderAddressMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResProviderAddressMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ResProviderAddressMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResProviderAddressMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResProviderAddressMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResProviderAddressMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回注册中心的提供者地址列表
     * </pre>
     *
     * Protobuf type {@code ResProviderAddressMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResProviderAddressMessage)
        ResProviderAddressMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcTestProto.internal_static_ResProviderAddressMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcTestProto.internal_static_ResProviderAddressMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResProviderAddressMessage.class, Builder.class);
      }

      // Construct using com.github.chenmingq.rpc.common.transport.protocol.RpcTestProto.ResProviderAddressMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddrListFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (addrListBuilder_ == null) {
          addrList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          addrListBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcTestProto.internal_static_ResProviderAddressMessage_descriptor;
      }

      @Override
      public ResProviderAddressMessage getDefaultInstanceForType() {
        return ResProviderAddressMessage.getDefaultInstance();
      }

      @Override
      public ResProviderAddressMessage build() {
        ResProviderAddressMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ResProviderAddressMessage buildPartial() {
        ResProviderAddressMessage result = new ResProviderAddressMessage(this);
        int from_bitField0_ = bitField0_;
        if (addrListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            addrList_ = java.util.Collections.unmodifiableList(addrList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.addrList_ = addrList_;
        } else {
          result.addrList_ = addrListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResProviderAddressMessage) {
          return mergeFrom((ResProviderAddressMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResProviderAddressMessage other) {
        if (other == ResProviderAddressMessage.getDefaultInstance()) return this;
        if (addrListBuilder_ == null) {
          if (!other.addrList_.isEmpty()) {
            if (addrList_.isEmpty()) {
              addrList_ = other.addrList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAddrListIsMutable();
              addrList_.addAll(other.addrList_);
            }
            onChanged();
          }
        } else {
          if (!other.addrList_.isEmpty()) {
            if (addrListBuilder_.isEmpty()) {
              addrListBuilder_.dispose();
              addrListBuilder_ = null;
              addrList_ = other.addrList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              addrListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAddrListFieldBuilder() : null;
            } else {
              addrListBuilder_.addAllMessages(other.addrList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResProviderAddressMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResProviderAddressMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<AddressBean> addrList_ =
        java.util.Collections.emptyList();
      private void ensureAddrListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          addrList_ = new java.util.ArrayList<AddressBean>(addrList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AddressBean, AddressBean.Builder, AddressBeanOrBuilder> addrListBuilder_;

      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public java.util.List<AddressBean> getAddrListList() {
        if (addrListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(addrList_);
        } else {
          return addrListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public int getAddrListCount() {
        if (addrListBuilder_ == null) {
          return addrList_.size();
        } else {
          return addrListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public AddressBean getAddrList(int index) {
        if (addrListBuilder_ == null) {
          return addrList_.get(index);
        } else {
          return addrListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public Builder setAddrList(
          int index, AddressBean value) {
        if (addrListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddrListIsMutable();
          addrList_.set(index, value);
          onChanged();
        } else {
          addrListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public Builder setAddrList(
          int index, AddressBean.Builder builderForValue) {
        if (addrListBuilder_ == null) {
          ensureAddrListIsMutable();
          addrList_.set(index, builderForValue.build());
          onChanged();
        } else {
          addrListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public Builder addAddrList(AddressBean value) {
        if (addrListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddrListIsMutable();
          addrList_.add(value);
          onChanged();
        } else {
          addrListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public Builder addAddrList(
          int index, AddressBean value) {
        if (addrListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddrListIsMutable();
          addrList_.add(index, value);
          onChanged();
        } else {
          addrListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public Builder addAddrList(
          AddressBean.Builder builderForValue) {
        if (addrListBuilder_ == null) {
          ensureAddrListIsMutable();
          addrList_.add(builderForValue.build());
          onChanged();
        } else {
          addrListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public Builder addAddrList(
          int index, AddressBean.Builder builderForValue) {
        if (addrListBuilder_ == null) {
          ensureAddrListIsMutable();
          addrList_.add(index, builderForValue.build());
          onChanged();
        } else {
          addrListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public Builder addAllAddrList(
          Iterable<? extends AddressBean> values) {
        if (addrListBuilder_ == null) {
          ensureAddrListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, addrList_);
          onChanged();
        } else {
          addrListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public Builder clearAddrList() {
        if (addrListBuilder_ == null) {
          addrList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          addrListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public Builder removeAddrList(int index) {
        if (addrListBuilder_ == null) {
          ensureAddrListIsMutable();
          addrList_.remove(index);
          onChanged();
        } else {
          addrListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public AddressBean.Builder getAddrListBuilder(
          int index) {
        return getAddrListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public AddressBeanOrBuilder getAddrListOrBuilder(
          int index) {
        if (addrListBuilder_ == null) {
          return addrList_.get(index);  } else {
          return addrListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public java.util.List<? extends AddressBeanOrBuilder>
           getAddrListOrBuilderList() {
        if (addrListBuilder_ != null) {
          return addrListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(addrList_);
        }
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public AddressBean.Builder addAddrListBuilder() {
        return getAddrListFieldBuilder().addBuilder(
            AddressBean.getDefaultInstance());
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public AddressBean.Builder addAddrListBuilder(
          int index) {
        return getAddrListFieldBuilder().addBuilder(
            index, AddressBean.getDefaultInstance());
      }
      /**
       * <pre>
       * 地址列表
       * </pre>
       *
       * <code>repeated .AddressBean addrList = 1;</code>
       */
      public java.util.List<AddressBean.Builder>
           getAddrListBuilderList() {
        return getAddrListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AddressBean, AddressBean.Builder, AddressBeanOrBuilder>
          getAddrListFieldBuilder() {
        if (addrListBuilder_ == null) {
          addrListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AddressBean, AddressBean.Builder, AddressBeanOrBuilder>(
                  addrList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          addrList_ = null;
        }
        return addrListBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResProviderAddressMessage)
    }

    // @@protoc_insertion_point(class_scope:ResProviderAddressMessage)
    private static final ResProviderAddressMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResProviderAddressMessage();
    }

    public static ResProviderAddressMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResProviderAddressMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResProviderAddressMessage>() {
      @Override
      public ResProviderAddressMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResProviderAddressMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResProviderAddressMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResProviderAddressMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public ResProviderAddressMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddressBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * ip
     * </pre>
     *
     * <code>string ip = 1;</code>
     */
    String getIp();
    /**
     * <pre>
     * ip
     * </pre>
     *
     * <code>string ip = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <pre>
     * 端口
     * </pre>
     *
     * <code>int32 port = 2;</code>
     */
    int getPort();

    /**
     * <pre>
     * 节点id
     * </pre>
     *
     * <code>int32 node = 3;</code>
     */
    int getNode();
  }
  /**
   * <pre>
   * 地址信息
   * </pre>
   *
   * Protobuf type {@code AddressBean}
   */
  public  static final class AddressBean extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddressBean)
      AddressBeanOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddressBean.newBuilder() to construct.
    private AddressBean(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddressBean() {
      ip_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddressBean();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddressBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 16: {

              port_ = input.readInt32();
              break;
            }
            case 24: {

              node_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcTestProto.internal_static_AddressBean_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcTestProto.internal_static_AddressBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddressBean.class, Builder.class);
    }

    public static final int IP_FIELD_NUMBER = 1;
    private volatile Object ip_;
    /**
     * <pre>
     * ip
     * </pre>
     *
     * <code>string ip = 1;</code>
     */
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * ip
     * </pre>
     *
     * <code>string ip = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <pre>
     * 端口
     * </pre>
     *
     * <code>int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int NODE_FIELD_NUMBER = 3;
    private int node_;
    /**
     * <pre>
     * 节点id
     * </pre>
     *
     * <code>int32 node = 3;</code>
     */
    public int getNode() {
      return node_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(2, port_);
      }
      if (node_ != 0) {
        output.writeInt32(3, node_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (node_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, node_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AddressBean)) {
        return super.equals(obj);
      }
      AddressBean other = (AddressBean) obj;

      if (!getIp()
          .equals(other.getIp())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (getNode()
          != other.getNode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + NODE_FIELD_NUMBER;
      hash = (53 * hash) + getNode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AddressBean parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressBean parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AddressBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddressBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AddressBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddressBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AddressBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AddressBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 地址信息
     * </pre>
     *
     * Protobuf type {@code AddressBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddressBean)
        AddressBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcTestProto.internal_static_AddressBean_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcTestProto.internal_static_AddressBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AddressBean.class, Builder.class);
      }

      // Construct using com.github.chenmingq.rpc.common.transport.protocol.RpcTestProto.AddressBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        ip_ = "";

        port_ = 0;

        node_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcTestProto.internal_static_AddressBean_descriptor;
      }

      @Override
      public AddressBean getDefaultInstanceForType() {
        return AddressBean.getDefaultInstance();
      }

      @Override
      public AddressBean build() {
        AddressBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public AddressBean buildPartial() {
        AddressBean result = new AddressBean(this);
        result.ip_ = ip_;
        result.port_ = port_;
        result.node_ = node_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AddressBean) {
          return mergeFrom((AddressBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AddressBean other) {
        if (other == AddressBean.getDefaultInstance()) return this;
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getNode() != 0) {
          setNode(other.getNode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AddressBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AddressBean) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object ip_ = "";
      /**
       * <pre>
       * ip
       * </pre>
       *
       * <code>string ip = 1;</code>
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * ip
       * </pre>
       *
       * <code>string ip = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ip
       * </pre>
       *
       * <code>string ip = 1;</code>
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ip
       * </pre>
       *
       * <code>string ip = 1;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ip
       * </pre>
       *
       * <code>string ip = 1;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <pre>
       * 端口
       * </pre>
       *
       * <code>int32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <pre>
       * 端口
       * </pre>
       *
       * <code>int32 port = 2;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 端口
       * </pre>
       *
       * <code>int32 port = 2;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int node_ ;
      /**
       * <pre>
       * 节点id
       * </pre>
       *
       * <code>int32 node = 3;</code>
       */
      public int getNode() {
        return node_;
      }
      /**
       * <pre>
       * 节点id
       * </pre>
       *
       * <code>int32 node = 3;</code>
       */
      public Builder setNode(int value) {
        
        node_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 节点id
       * </pre>
       *
       * <code>int32 node = 3;</code>
       */
      public Builder clearNode() {
        
        node_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AddressBean)
    }

    // @@protoc_insertion_point(class_scope:AddressBean)
    private static final AddressBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AddressBean();
    }

    public static AddressBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddressBean>
        PARSER = new com.google.protobuf.AbstractParser<AddressBean>() {
      @Override
      public AddressBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressBean(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddressBean> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AddressBean> getParserForType() {
      return PARSER;
    }

    @Override
    public AddressBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqConnectServerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReqConnectServerMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResProviderAddressMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResProviderAddressMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressBean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddressBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rRpcTest.proto\"5\n\027ReqConnectServerMessa" +
      "ge\022\014\n\004port\030\001 \001(\005\022\014\n\004node\030\002 \001(\005\";\n\031ResPro" +
      "viderAddressMessage\022\036\n\010addrList\030\001 \003(\0132\014." +
      "AddressBean\"5\n\013AddressBean\022\n\n\002ip\030\001 \001(\t\022\014" +
      "\n\004port\030\002 \001(\005\022\014\n\004node\030\003 \001(\005BB\n2com.github" +
      ".chenmingq.rpc.common.transport.protocol" +
      "B\014RpcTestProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ReqConnectServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReqConnectServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReqConnectServerMessage_descriptor,
        new String[] { "Port", "Node", });
    internal_static_ResProviderAddressMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResProviderAddressMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResProviderAddressMessage_descriptor,
        new String[] { "AddrList", });
    internal_static_AddressBean_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AddressBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddressBean_descriptor,
        new String[] { "Ip", "Port", "Node", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
